### PR TITLE
Fix major networking bug.

### PR DESCRIPTION
**Pull request by jessetilro**
The networking was defect, since a certain message class was not
serializable.

### CODE REVIEW

**Comment by dmalarev** [comment]
Alright, I'll see what i can do to fix it.
Good work finding it.

**Comment by dmalarev** [comment]
I think I see the issue.
I think it's the fact that the class contains an item (ArrayList), that can not be serialized

**Comment by jessetilro** [comment]
Exactly, that was what I thought as well. On top of that I believe the class was not registered with the Serializer yet in the first place. I will make an issue to fix this in Sprint 4.

**Comment by dmalarev** [comment]
For the rest the code looks good, so this can be merged.

**Pull request merged**
