### PR TITLE
Added parameter for plasma leak event

### PR DESCRIPTION
**Pull request by dmalarev**

### CODE REVIEW

**Comment by dalderliesten** [comment]
@dmalarev Please always add a description to your pull requests.

**Comment by jessetilro** [comment]
LGTM

**Comment by wouterz** [comment]
massive pull request approved

**Comment by jessetilro** [comment]
You just merged this into an old branch that has already been merged into release. I suggest you make a new PR with these changes, this time for the release branch or your own feature branch.

**Pull request merged**
