### PR TITLE
Fix bugs with parameters.

### PR DESCRIPTION
**Pull request by jessetilro**
With the changes introduced in PR #310, some defects in the Event
Parameter subsystem were introduced as well. These are fixed by this
commit. Also did some refactoring and optimization.

### CODE REVIEW

**Comment by jessetilro** [comment]
Still doing some playtesting. But feel free to review the changes so far.

**Comment by jessetilro** [comment]
Done, everything should run smoothly again.

**Comment by dalderliesten** [comment]
Glad to see this has been fixed, looks good to me.

**Comment by FlorisXll** [comment]
LGTM

**Comment by dmalarev** [comment]
Looks good

**Pull request merged**
