### PR TITLE
Refactor scene

### PR DESCRIPTION
**Pull request by wouterz**
Give defining the objects its own class. Later on i intend to maybe write some create/factory methods for this to get shorter and cleaner code that can be tested better as well

### CODE REVIEW

**Comment by wouterz** [comment]
https://updates.jmonkeyengine.org/maven/ is currently down, so travis build will fail

**Comment by jessetilro** [comment]
The builds of all your commits are failing on the CI server, did you test and build the program intermediately?

**Comment by dalderliesten** [comment]
Until the project/checks are fixed, whatever the reason may be, I suggest we hold out on merging!

**Comment by dmalarev** [comment]
Code looks good to me

**Comment by dalderliesten** [comment]
Looks good to me!

**Pull request merged**
