### PR TITLE
Mini game asteroid impact

### PR DESCRIPTION
**Pull request by FlorisXll**
For the Server side: added the parameter which can be 0 or 1, Energy Shield or Hyperdrive respectively. 

Related PR client: https://github.com/jessetilro/pixelperfect-client/pull/26

### CODE REVIEW

**Comment by jessetilro** [comment]
Can you resolve the conflicts first?

**Comment by FlorisXll** [comment]
I had no merge conflicts, but merged release into this branch.

**Comment by jessetilro** [comment]
Well, whatever you call it: GitHub stated the branch could not be automatically merged before you pulled release into your branch, that's what I meant.

**Comment by FlorisXll** [comment]
Correct, which is weird ofc but it'll have to do.

**Comment by jessetilro** [comment]
LGTM

**Comment by dmalarev** [comment]
LGTM

**Pull request merged**
