### PR TITLE
Game refactor

### PR DESCRIPTION
**Pull request by FlorisXll**
Refactored a few things following the TA's feedback. Ignore the first commit, as this was to switch workplaces.

Also resolved nearly all static warnings. The setGame() method in ServerListener is still a problem that can be refactored later.

### CODE REVIEW

**Comment by jessetilro** [comment]
Wow, why all those indentation changes?

**Comment by dmalarev** [comment]
Looks good. Works nicely

**Comment by dalderliesten** [comment]
Looks nice, lots of indentation things.

**Comment by FlorisXll** [comment]
That is because of the fact that David had newly imported the project and pushed wrong indentation duo to Checkstyle configurations which he had not updated yet.

**Pull request merged**
