### PR TITLE
Idle game

### PR DESCRIPTION
**Pull request by dmalarev**
Added the server side implementation of the idle mini-game.

### CODE REVIEW

**Comment by wouterz** [comment]
LGTM

**Comment by jessetilro** [comment]
LGTM, will do a manual test shortly.

**Comment by jessetilro** [comment]
Play tested, works nicely. During one run the app crashed due to NullPointerExceptions but this is an issue with the networking components. After a reboot everything went smoothly. My only concern is that you can buff the ship past 100 health points, is this a problem?

**Comment by dalderliesten** [comment]
@jessetilro , yeah, let me add in a blocker for that.

**Pull request merged**
