### PR TITLE
Server role allocation.

### PR DESCRIPTION
**Pull request by jessetilro**
The role allocation is now verified server-side. The process of joining the game will be further tuned in upcoming PR's, fixing networking issues.

Was developed and should therefore be tested in parallel with PR https://github.com/jessetilro/pixelperfect-client/pull/52.

Will fix merge conflicst right away.

### CODE REVIEW

**Comment by dalderliesten** [comment]
All of your checks have failed.

**Comment by jessetilro** [comment]
Interesting, local tests passed. Will first fix merge conflicts and them take a look at how I can make the build pass. Please bear with me.

**Comment by jessetilro** [comment]
Everything should be OK now.

**Comment by wouterz** [comment]
works! There is one edge case where it does not work: Pick role, press back arrow and pick same role. Role is then denied.

**Comment by jessetilro** [comment]
Ok, that is probably because the client does not disconnect in the mean time? Will investigate the issue in next PR, is that ok? (This PR is already to big.)

**Comment by wouterz** [comment]
perfect

**Comment by dalderliesten** [comment]
A lot more streamlined, lgtm.

**Pull request merged**
