### PR TITLE
Refactor Event Factory

### PR DESCRIPTION
**Pull request by jessetilro**
Refactored the Event Factory implementation to an entire new subsystem. Implemented the Abstract Factory design pattern and the Builder design pattern in this new subsystem. Also introduced an enumeration of Event Types, and integrated the Event Parameters components with building and storing Events.

Maintained test coverage and fixed all static errors.
Contributes to resolving Issues #190, #161 and #201.

In the next PR for this feature branch I will focus on integrating the Event Parameters with the networking components and making sure they are properly synchronized and validated with the client. Afterwards, this feature should be ready to be merged in the release.

### CODE REVIEW

**Comment by dmalarev** [comment]
in the test methods, there are a couple of missing braches when i run a coverage test.
Other than that, nicely done.

**Comment by dalderliesten** [comment]
@dmalarev Could you mark which branches are missing?

**Comment by FlorisXll** [comment]
I would create some subpackages.

**Comment by dmalarev** [comment]
the missing braches are:
EventReader.getByType() (missing 1 branch on data != null)
EventReader.has() (missing 1 branch)
EventParameter.equals() (3 branches missing at the generic check)

**Comment by jessetilro** [comment]
@dalderliesten We discussed this over Skype: these branches where hard to test so we decided the test suites are fine as they are right now.

**Comment by jessetilro** [comment]
I will take a look at the missing branches in the next PR. However, we don't have time this week to achieve 100% coverage everywhere. We need a lot of features, and since I already tested the changes quite extensively to achieve 96% branch coverage for this package it is not a big deal in my opinion. As for the packages, I will try to organize this in the next PR as well. For now I would like to move forward to get the feature completely integrated.

**Comment by FlorisXll** [comment]
You forgot to create subpackages.

**Comment by jessetilro** [comment]
@FlorisXll Please read comment above you comment.

**Comment by wouterz** [comment]
Nothing new to add, merging

**Pull request merged**
