### PR TITLE
Refactor event synchronization.

### PR DESCRIPTION
**Pull request by jessetilro**
Refactored the entire network messaging system. All Event validation is done server-side now. In short this has two benefits:

- Increase of maintainability because of less shared components between client and server.
- Fixes bug described in the issue referenced below (227).

Developed (and should therefore be tested) in parallel with PR https://github.com/jessetilro/pixelperfect-client/pull/27.
Resolves Issues #224, #226 and #227.

### CODE REVIEW

**Comment by dmalarev** [comment]
Lgtm

**Comment by dalderliesten** [comment]
Looks great, be sure to check the server PR.

**Comment by FlorisXll** [comment]
*client

**Comment by wouterz** [comment]
LGTM

**Pull request merged**
