### PR TITLE
Release v0.4.0

### PR DESCRIPTION
**Pull request by jessetilro**
Release of the stable working version of the server application as a result of Sprint 4.

### CODE REVIEW

**Comment by dalderliesten** [comment]
Looks great!

**Comment by dmalarev** [comment]
Looks good

**Comment by jessetilro** [comment]
There's a static error, reported by CheckStyle:  HideUtilityClassConstructor!

**Comment by dalderliesten** [comment]
Re-approved after the hotfix, if the tests pass.

**Comment by wouterz** [comment]
LGTM

**Comment by FlorisXll** [comment]
LGTM

**Pull request merged**
