### PR TITLE
Routegenerator

### PR DESCRIPTION
**Pull request by FlorisXll**
Issue #44 

Implemented a simple route generator for now which is semi-hard coded: the route generator knows which RouteNodes exist.

I have also implented an easy Tuple utility class which helps me implement an easy-to-use list of Tuples. This can later be used to make two-way choices.

**Note**: 
- there are still CheckStyle warnings present in other parts of the code.
- no tests are made for this code yet.

### CODE REVIEW

**Comment by jessetilro** [comment]
I suggest you write some test cases before merging this. We already have a lot of cleaning up to do before the release of the sprint.

**Comment by FlorisXll** [comment]
I will, probably good to wait for the merging of the tests by David. #71

**Comment by dmalarev** [comment]
LGTM so far

**Comment by FlorisXll** [comment]
Should be good to go now.

**Comment by wouterz** [comment]
Looks good, but why an arraylist of tuples instead of a binary tree?

**Pull request merged**
