### PR TITLE
Redone the branch to the changes of the latest merge

### PR DESCRIPTION
**Pull request by dmalarev**
Issue #67 

Reopened under another branch because it didn't register my merge conflicts.

### CODE REVIEW

**Comment by dalderliesten** [comment]
I encourage you to assign somebody to review this.

**Comment by dmalarev** [comment]
I added more code to begin on Issue #63.
The rest supposedly needs to be done in the android client (receiving + working with EventsMessages and sending the new Log)

**Comment by wouterz** [comment]
LGTM

**Comment by dalderliesten** [comment]
Looks good to me.

**Pull request merged**
